site_name: Facets Documentation
site_url: https://www.facets.cloud/documentation
site_dir: documentation
docs_dir: markdown
google_analytics:
  - UA-194596364-1
  - auto
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: media/fav.png
  favicon: media/fav.png
  features:
    - navigation.instant
    - navigation.tracking
  palette:
    primary: 005EA6
nav:
  - Introduction: 'index.md'
  - Getting Started:
      - Prerequisites: 'getting_started/prerequisites.md'
      - Concepts: 'on_boarding/concepts.md'
      - Get your Control Plane: 'on_boarding/control_plane.md'
      - Create a Stack: 'on_boarding/create_stack.md'
      - Create a Cluster: 'on_boarding/create_cluster.md'
      - Video Tutorial: 'getting_started/demo.md'
  - Operate your Cluster:
      - Observability: 'tools/observability.md'
      - Compliance & Security: 'tools/compliance.md'
  - Roadmap:
      - 'roadmap/roadmap.md'
      - 'roadmap/request.md'


markdown_extensions:
  - fenced_code