site_name: Facets Documentation
site_dir: documentation
google_analytics:
  - UA-194596364-1
  - auto
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  logo: media/fav.png
  favicon: media/fav.png
  features:
    - navigation.instant
    - navigation.tracking
  palette:
    primary: 005EA6
nav:
  - Home: index.md
  - Getting Started:
      - Prerequisites: 'getting_started/prerequisites.md'
      - Demo: 'getting_started/demo.md'
  - Operate your Cluster:
      - Observability: 'tools/observability.md'
      - Compliance & Security: 'tools/compliance.md'
  - Roadmap:
      - 'roadmap/roadmap.md'
      - 'roadmap/request.md'


markdown_extensions:
  - fenced_code